### ISSUE TITLE
The Horror....The Horror....  lengths of reactomeSets...

### ISSUE THREAD

**Issue by arcolombo** [RamsinghLab/TxDbLite#12]
there is an upcoming PR, that will solve this.... speedSage derailed because when reactomeSets issues the genes found in the cache which intersected the kexp,  it forces that the rownames are unique....which means that for multiple genes found in various reactome ID.... it adds a trailing one.... this one is the one to rule them all....

so the solution_ is to not have the rownames be the genes found amongst the domain of pw-IDs, (they are non-unique)....

 nchar(rownames(mp))
 [1] 18 18 18 18 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 18 19 19 18 19
[26] 19 19 18 18 19 19 19 18 19 19 19 19 18 19 19 19 19 19 18 18 18 18 18 18 19
[51] 19 19 19 19 19 19 19 19 19 18 18 18 18 18

where all ensembl original name IDs have nchar of 18

all(nchar(rownames(coll)[1:(length(rownames(coll))-97)])==18)

incoming...

**Comment by arcolombo** [comment]
the PR fixed the issue with connecting speedSage and Arkas....when travis passes this can be closed...

**Comment by arcolombo** [comment]
travis is failing because it requires  all the suggests packages.... fixing now.

**Comment by ttriche** [comment]
Ah shit. That's my fault :-(

--t

**Comment by arcolombo** [comment]
np. no brainer to fix.

**Comment by arcolombo** [comment]
closing.
