### ISSUE TITLE
Biostrings  , utils  namespace conflict for head/tail

### ISSUE THREAD

**Issue by arcolombo** [RamsinghLab/TxDbLite#15]
so ensDbLiteFromFasta has a line using require(),  but this should prolly be omitted because these required functions are imported.

the other option is that a WARNING is issued from TxDbLite   that implies one should importFROM biostrings to not have this warning..

 Warning: replacing previous import 'Biostrings::tail' by 'utils::tail' when
vignettes/makeTxDbLiteAnnotationLibrary.html: Warning: replacing previous import 'Biostrings::head' by 'utils::head' when

**Comment by ttriche** [comment]
or maybe be more explicit ("take my advice, I'm not using it!" ... oops)

I wonder what I'm using "utils" for ?

--t

On Tue, Aug 9, 2016 at 3:02 PM, Anthony R. Colombo <notifications@github.com

**Comment by arcolombo** [comment]
Let me patch in my changes first. I will leave any tricky ones alone (for you :P)
