### ISSUE TITLE
R CMD check checking for non-ASCII characters warning

### ISSUE THREAD

**Issue by arcolombo** [RamsinghLab/TxDbLite#17]
- checking data for non-ASCII characters ... WARNING
  Warning: found non-ASCII strings
  'Loss of proteins required for interphase microtubule organization<c2><a0>from the centrosome' in object 'ensemblToReactome'
  'Loss of proteins required for interphase microtubule organization<c2><a0>from the centrosome' in object 'reactomePathways'

**Comment by arcolombo** [comment]
found the terrorists.

> showNonASCII(yy$name)
> 888: Loss of proteins required for interphase microtubule organization<c2><a0>from the centrosome
> 1146: Loss of proteins required for interphase microtubule organization<c2><a0>from the centrosome
> 1371: Loss of proteins required for interphase microtubule organization<c2><a0>from the centrosome
> 1395: Loss of proteins required for interphase microtubule organization<c2><a0>from the centrosome
> 1761: Loss of proteins required for interphase microtubule organization<c2><a0>from the centrosome
> 3041: Loss of proteins required for interphase microtubule organization<c2><a0>from the centrosome
> 3634: Loss of proteins required for interphase microtubule organization<c2><a0>from the centrosome
> 3729: Loss of proteins required for interphase microtubule organization<c2><a0>from the centrosome
> 3930: Loss of proteins required for interphase microtubule organization<c2><a0>from the centrosome
> 4211: Loss of proteins required for interphase microtubule organization<c2><a0>from the centrosome
> 4239: Loss of proteins required for interphase microtubule organization<c2><a0>from the centrosome
> 6377: Loss of proteins required for interphase microtubule organization<c2><a0>from the centrosome
> 8905: Loss of proteins required for interphase microtubule organization<c2><a0>from the centrosome
> 9549: Loss of proteins required for interphase microtubule organization<c2><a0>from the centro

a simple gsub should solve.

**Comment by ttriche** [comment]
Oh god I remember tearing this out at one point.  See if the fix is already in my branch 

--t

**Comment by arcolombo** [comment]
aw shit.

**Comment by arcolombo** [comment]
this one looks like the fix.   you worked on it....  thanks ...let me polish and test...

6cebb1ac80d5db089043f1ee9148167cc037e549

**Comment by arcolombo** [comment]
this is solved via @ttriceh's master ... closing
