### ISSUE TITLE
Reactome and biomaRt Support

### ISSUE THREAD

**Issue by arcolombo** [RamsinghLab/TxDbLite#2]
Per our conversation @ttriche current issue with supporting biomaRt pending production release, and reactome support.

**Comment by ttriche** [comment]
Forked -- working on this later this afternoon (post-meetings)

--t

**Comment by ttriche** [comment]
begun: https://github.com/ttriche/TxDbLite

**Comment by ttriche** [comment]
Alright, it's slow but it works.  Incoming commit maps ENS[TG] to Reactome at either level.

**Comment by arcolombo** [comment]
awesome!!
