### ISSUE TITLE
dry running flag for vignette bioconductor, optional saving, mandatory processing

### ISSUE THREAD

**Issue by arcolombo** [RamsinghLab/TxDbLite#21]
so I'm adding a dryRun flag to allow for vignettes compatible with BioC.

the workflow will branch off dbConnect, and dbWriteTable to allow for optional directions; but still will print a db name (which would be a decent indicator for vignette testing).   no path-ing  and saving of objects in a vignette is allowed.

Sincerely,
D. Mustaine

**Comment by ttriche** [comment]
Mustaine got kicked out of Metallica for being an annoying drunk, you know

--t

**Comment by arcolombo** [comment]
yes. young and dumb.  he claims to be wiser now.

**Comment by arcolombo** [comment]
Leo Tolstoy when he was young used to get in bar fights while
gambling......  young and dumb.

**Comment by arcolombo** [comment]
upcoming PR will solve this. the vignette is passing.  0 warnings.  4 notes.  please forgive bad grammar.  speed is better...

**Comment by arcolombo** [comment]
clsiing
