### ISSUE TITLE
support data frames specific for vignette  *DbLiteFromFasta

### ISSUE THREAD

**Issue by arcolombo** [RamsinghLab/TxDbLite#22]
for a vignette build it is not possible to use system.file(somePath/someFile).   on my local end /usr  I always have to change mode 766/777 type of thing.

one idea is to stuff the ERCC.fa -> ERCC-dataFrame, and allow for the *DbLiteFromFasta to support a data frame.  The structure would be the same (ERCC,ENS,REP)  the workflow should have a bit more complexity.

if the input is a FASTA , then proceed using Rsamtools (scanFa, indexFa, FaFile)
if the input is a dataFrame,  then  merge with the existing functions at seqnames(txs) (skipping the Rsamtools preparatory lines).

the idea/motivation is to use  data("ERCC/ENS/REP.rda",package=TxDbLite)  in the vignette instead of a system.file command.   (this avoids change directory)

**Comment by arcolombo** [comment]
a few typos....edited..

**Comment by arcolombo** [comment]
one alternative is to store in /extdata  (which can have .fa.gz files)  and then use system.path.  but I am not sure if this will fail on the BioC.     

It is important to note how a BioC can path to a file, and what access it has....

**Comment by ttriche** [comment]
That's the typical solution 

--t
