### ISSUE TITLE
strunshift phrasing issue

### ISSUE THREAD

**Issue by arcolombo** [RamsinghLab/TxDbLite#25]
The original phrasing here is 
strunshift <- function(w, x, y=" ", z=0) {
  paste(append(str2vec(w, y), x, z collapse=y))
}
~        

However, collapse is parameter for paste,  so the phrasing may be incorrect above.
is this it?    append(str2vec(w,y),x)  then paste to z ? 
strunshift <- function(w, x, y=" ", z=0) {
  paste(append(str2vec(w, y), x) ,z ,collapse=y)
}
~

**Comment by ttriche** [comment]
oh gross.  should be something like

strunshift <- function(w, x, y=" ", z=0) {
  ww <- append(str2vec(w, y), x, z)
  paste(ww, collapse=y)
}

strunshift("foo bar baz", "qux", y=" ", 0)

# [1] "qux foo bar baz"

strunshift("foo;bar baz", "qux", y=";", 1)

# [1] "foo;qux;bar baz"

I don't think I ended up using the function much, which is a good thing :-o

--t

**Comment by arcolombo** [comment]
ok. verified on my end.  solved.
