### ISSUE TITLE
onLoad  sealed namespace issue

### ISSUE THREAD

**Issue by arcolombo** [RamsinghLab/TxDbLite#27]
hi so the namespace is sealed once a package is loaded.  so the onLoad function that loads a TxDbLite db into the namespace is not feasible (?)
## 

.onLoad <- function(libname, pkgname)
{
  ns <- asNamespace(pkgname)
  path <- system.file("extdata", package=pkgname)
  files <- dir(path)
  for(i in seq_len(length(files))){
   # db <- EnsDbLite(system.file("extdata", files[[i]], package=pkgname,
    #                lib.loc=libname))
    db<-EnsDbLite(files[[i]],path)
    objname <- sub(".sqlite$","",files[[i]])
    unlockBinding(db,ns)
    assign(objname, db, envir=ns)
    namespaceExport(ns, objname)
  }
}

ERROR error in namespaceExport(ns, objname) : 
  cannot add to exports of a sealed namespace

so I'm not sure how we were able to load a DB on package loading previously (?)

**Comment by arcolombo** [comment]
One alternative is to save the sqlite db as rda and store into /data dir and use data(db,package=ensdblite.species.build) to load in Namespace

**Comment by ttriche** [comment]
odd, but solvable I suppose; either data(db, package=pkg) or features(db)

I should have time to look into this and maybe get a clean solution later
this afternoon (working on slides & manuscripts ATM)

--t

**Comment by arcolombo** [comment]
data(db.rda) will _not_ work.   features is not defined.  but transcripts(EnsDbLite(db)) certainly is an option.

**Comment by ttriche** [comment]
so the constructor can load the db from the sqlite file?  I guess thats fine

--t

**Comment by arcolombo** [comment]
yes saving the sqlite as rda was a bad idea.
saving the transcripts(TxDbLite(sqlite))   as an Rda  worked just find (it is just a GRanges()). 

is the transcript(EnsDbLite(x.sqlite)) _only_ used by arkas::annotateFeatures(kexp)  ?  need to make sure if I go this route then it is ok.

the other route is to not care and let users path themselves... just describe in a vingette.

**Comment by ttriche** [comment]
the idea is to load the package as a full fledged TxDb-like object, hence
the name (TxDbLite) -- one can retrieve genes, transcripts, promoters etc.
from the object.  Just saving the result as an .rda defeats the purpose of
having the information in a compact SQLite database which can be
"reinflated" to give the other types of information.  Another alternative
is to use full TxDb objects but this can get ugly for Ensembl... not sure
what the best choice is.  Although it would free us of any responsibility
to maintain TxDbLite if we did the latter approach (i.e., crank out TxDb
objects for Ensembl)... instead we'd be supporting the TxDb objects.  Not
sure which is the worse poison

--t

**Comment by arcolombo** [comment]
Ok.  Let me try a straight up load() command.  Maybe we dont need a namespace export command.  Updates soon.

**Comment by arcolombo** [comment]
i made a mistake.   I was checking the namespace using the ls() command.   the ls() command came up empty, however the namespace is properly being exported.  this can be closed.  TxDbLite is working fine.
library(EnsDbLite.Hsapiens.81)

> ls()
> character(0)
> 
> > EnsDbLite.Hsapiens.81
> > EnsDbLite :
> > |package_name: EnsDbLite.Hsapiens.81
> > |db_type: EnsDbLite
> > |type_of_gene_id: Ensembl Gene ID
> > |created_by: TxDbLite 1.9.113
> > |creation_time: Fri Aug 19 14:26:41 2016
> > |organism: Homo sapiens
> > |genome_build: GRCh38
> > |source_file: ~/Documents/github_repos/arkasData/inst/extdata/fasta/Homo_sapiens.GRCh38.81.cdna.all.fa.gz
> > | 175372 transcripts from 38530 bundles (genes).
